import React,{useState,useEffect} from 'react';
import {Button} from './components/ui/button';
import {Slider} from './components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from './components/ui/tabs';
import {moods} from '../../../../../../src/lib/palettes-v2';
import {fontMap,MANNER,variationFor,opticalStroke} from '../../../../../../src/lib/palettes';
import './gallery.css';
const variants=[['A','한 축 집중','도구를 고르고, 한 줄로 조절'],['B','세 축 한눈','모든 값을 한 번에 확인'],['C','5칸 터치','드래그 없이 한 번에 선택'],['D','한 칸씩','큰 ± 버튼으로 정확하게']];
const samples=['밥 먹었어?','수업은 끝났는데\n할 말이 남았다','말할곳이없어서여기에쓴다','GPA 4.5는 거짓말','내가 하고 싶은 말은\n사실 이게 아니었는데\n지금은 이것밖에\n떠오르지 않는다','오늘 하루가 어땠는지\n아무도 묻지 않아서\n나는 여기에\n한 줄을 남긴다\n사흘이면 충분하다'];
const faces=[['deulseok','유머있는'],['ttoryeot','당당한'],['chabun','차분한'],['doran','다정한']];
const names=[['아주 작게','작게','보통','크게','아주 크게'],['아주 빠르게','빠르게','보통','천천히','아주 천천히'],['아주 가볍게','가볍게','보통','묵직하게','아주 묵직하게']];
export default function Gallery(){
 const [layout,setLayout]=useState('all'),[step,setStep]=useState(3),[sample,setSample]=useState(1),[font,setFont]=useState('deulseok'),[values,setValues]=useState([3,3,3]),[manner,setManner]=useState(0),[color,setColor]=useState(0),[axis,setAxis]=useState(0),[compare,setCompare]=useState(false),[scene,setScene]=useState('now'),[notice,setNotice]=useState(''),[fontReady,setFontReady]=useState(true);
 const labels=['크기','빠르기',MANNER[font]?'말투':'무게'];
 const set=(i,n)=>{if(i===2&&MANNER[font])setManner(n-1);else setValues(v=>v.map((x,j)=>i===j?Math.max(1,Math.min(5,n)):x))};
 const get=i=>i===2&&MANNER[font]?manner+1:values[i];
 const words=i=>i===2&&MANNER[font]?MANNER[font].labels:names[i];
 const reset=()=>{setValues([3,3,3]);setManner(0)};
 useEffect(()=>{setCompare(false);setNotice('')},[step,font]);
 useEffect(()=>{let alive=true;const family=fontMap[font].split(',')[0];document.fonts.load(`24px ${family}`,'가나다').then(()=>{if(alive)setFontReady(document.fonts.check(`24px ${family}`,'가나다'))});return()=>alive=false},[font]);
 const display=compare?[3,3,3]:values;
 const maxLine=Math.max(...samples[sample].split('\n').map(x=>x.length));
 const base=Math.min([28,36,44,52,60][display[0]-1],270/(maxLine*.9));
 const typeStyle={fontFamily:fontMap[font],fontSize:base,fontWeight:[300,400,500,600,700][display[2]-1],fontVariationSettings:variationFor(font,[300,400,500,600,700][display[2]-1],compare?0:manner),WebkitTextStrokeWidth:`${opticalStroke[font]?.[display[2]-1]??0}em`,transform:`scaleX(${[.7,.85,1,1.15,1.3][display[1]-1]}) skewX(${[-32,-24,0,0,0][display[1]-1]}deg)`};
 const actualColor=moods[color];
 const TabsAxis=()=> <Tabs value={String(axis)} onValueChange={v=>setAxis(Number(v))}><TabsList className="axis-tabs">{labels.map((l,i)=><TabsTrigger value={String(i)} key={i}>{l}</TabsTrigger>)}</TabsList></Tabs>;
 const stops=i=><div className="step-buttons">{words(i).map((w,j)=><Button key={w} variant={get(i)===j+1?'default':'outline'} aria-label={`${labels[i]} ${w}`} aria-pressed={get(i)===j+1} onClick={()=>set(i,j+1)}>{words(i).length===2?w:j+1}</Button>)}</div>;
 const slider=i=><><div className="value-row"><span>{labels[i]}</span><strong>{words(i)[get(i)-1]}</strong></div>{words(i).length===2?stops(i):<Slider aria-label={labels[i]} aria-valuetext={words(i)[get(i)-1]} min={1} max={5} step={1} value={[get(i)]} onValueChange={v=>set(i,v[0])}/>}<div className="range-labels"><span>{words(i)[0]}</span><span>{words(i).at(-1)}</span></div></>;
 return <div className="gallery"><div className="gallery-toolbar"><div><h1>MEGAFONT · 편집 패널 비교</h1><p>4가지 배치 × 3개 단계 · 편집값을 공유합니다</p></div><div className="gallery-options"><label>배치<select value={layout} onChange={e=>setLayout(e.target.value)}><option value="all">네 가지 나란히</option>{variants.map(([id,name])=><option key={id} value={id}>{id} · {name}</option>)}</select></label><label>견본 문장<select value={sample} onChange={e=>setSample(+e.target.value)}>{samples.map((s,i)=><option value={i} key={i}>{i+1}. {s.replaceAll('\n',' ')}</option>)}</select></label><label>서체<select value={font} onChange={e=>setFont(e.target.value)}>{faces.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><div className="stage-switch">{[3,4,5].map((n,i)=><Button key={n} variant={step===n?'default':'outline'} onClick={()=>setStep(n)}>{n} · {['조율','색','확인'][i]}</Button>)}</div>{!fontReady&&<p>선택한 서체를 불러오지 못해 대체 서체로 표시 중입니다.</p>}</div>
 <div className={`gallery-grid ${layout==='all'?'':'single'}`}>{variants.filter(v=>layout==='all'||v[0]===layout).map(([id,name,desc])=><section className="proposal" key={id} aria-label={`${id} ${name}`}><div className="proposal-title"><h2>{id} · {name}</h2><p>{desc}</p></div><div className={`phone variant-${id}`}><header className="phone-header"><Button variant="ghost" aria-label="이전 단계" disabled={step===3} onClick={()=>setStep(step-1)}>←</Button><span>{step} / 5 · {['조율','색','미리보기'][step-3]}</span></header><div className="phone-title"><h3>{['내 말의 느낌을 맞춰요','내 말에 색을 입혀요','벽에서는 이렇게 보여요'][step-3]}</h3>{step===5&&<p>보내기 전, 마지막으로 확인해주세요.</p>}</div>
 <div className={`preview-stage stage-${step}`}>
 {step===5?<div className={`wall-preview ${scene==='later'?'later':''}`}><div className="wall-label">캠퍼스 벽 · 16:10</div>{scene==='later'&&<><span className="neighbor n1">오늘도 여기</span><span className="neighbor n2">다들 수고했어</span></>}<div className="wall-message" style={{background:actualColor.bg,color:actualColor.text}}><div style={typeStyle}>{samples[sample]}</div></div></div>:<div className={step===4?'colored-message':'plain-message'} style={step===4?{background:actualColor.bg,color:actualColor.text}:undefined}><div style={typeStyle}>{samples[sample]}</div></div>}
 {step===3&&<Button className="compare-button" variant="ghost" aria-label="누르는 동안 원본 비교" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setCompare(true)}} onPointerUp={()=>setCompare(false)} onPointerCancel={()=>setCompare(false)} onLostPointerCapture={()=>setCompare(false)} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();setCompare(true)}}} onKeyUp={()=>setCompare(false)} onBlur={()=>setCompare(false)}>{compare?'원본 보는 중':'원본 비교'}</Button>}
 </div>
 <div className="editor-panel">
 {step===3&&<>{id!=='B'&&<TabsAxis/>}{id==='A'&&<div className="one-slider">{slider(axis)}</div>}{id==='B'&&<div className="all-sliders">{labels.map((_,i)=><div key={i}>{slider(i)}</div>)}</div>}{id==='C'&&<div className="touch-panel"><div className="value-row"><span>{labels[axis]}</span><strong>{words(axis)[get(axis)-1]}</strong></div>{stops(axis)}<div className="range-labels"><span>{words(axis)[0]}</span><span>{words(axis).at(-1)}</span></div></div>}{id==='D'&&<div className="increment-panel"><Button variant="outline" aria-label={`${labels[axis]} 한 단계 줄이기`} disabled={get(axis)===1} onClick={()=>set(axis,get(axis)-1)}>−</Button><div><strong>{words(axis)[get(axis)-1]}</strong><span>{get(axis)} / {words(axis).length}</span></div><Button variant="outline" aria-label={`${labels[axis]} 한 단계 늘리기`} disabled={get(axis)===words(axis).length} onClick={()=>set(axis,get(axis)+1)}>＋</Button></div>}<Button className="reset-small" variant="ghost" onClick={reset}>조율 초기화</Button></>}
 {step===4&&<><div className="value-row"><span>글자와 바탕의 조합</span><strong>{color+1} / 10</strong></div><div className={`swatches colors-${id}`} role="group" aria-label="색 조합">{moods.map((m,i)=><button key={m.id} style={{background:m.bg,color:m.text}} aria-label={`${m.name} 색 조합`} aria-pressed={color===i} onClick={()=>setColor(i)}>가{color===i&&<span aria-hidden="true">✓</span>}</button>)}</div></>}
 {step===5&&<><Tabs value={scene} onValueChange={setScene}><TabsList className="scene-tabs"><TabsTrigger value="now">꽂혀 있는 동안</TabsTrigger><TabsTrigger value="later">그 뒤 3일</TabsTrigger></TabsList></Tabs><p className="scene-caption">{scene==='now'?'내 말이 벽에 크게 나타나요.':'다른 말들과 함께 머물다가 사라져요.'}</p><div className="edit-links"><Button variant="outline" onClick={()=>setStep(3)}>조율 수정</Button><Button variant="outline" onClick={()=>setStep(4)}>색 수정</Button></div></>}
 <Button className="next-button" onClick={()=>step<5?setStep(step+1):setNotice('시안 확인 완료 · 실제로 전송하지 않았어요.')}>{['색 고르기 →','미리보기 →','이대로 보낼게요'][step-3]}</Button>{notice&&<p className="demo-notice" role="status">{notice}</p>}
 </div></div></section>)}</div><p className="gallery-footnote">비교용 프로토타입 · 실제 전송 없음 · 최종 벽 배치·조판은 본 앱과 연결하기 전의 근사 표현입니다.</p></div>
}
