import React,{useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Button} from './components/ui/button';
import {Slider} from './components/ui/slider';
import './style.css';
const axes=[{name:'크기',ends:['작게','크게'],words:['아주 작게','작게','보통','크게','아주 크게']},{name:'빠르기',ends:['느리게','빠르게'],words:['아주 느리게','느리게','보통','빠르게','아주 빠르게']},{name:'무게',ends:['가볍게','무겁게'],words:['아주 가볍게','가볍게','보통','무겁게','아주 무겁게']}];
function Knob({value,onChange,axis}){
 const start=useRef(null),set=v=>onChange(Math.max(1,Math.min(5,v)));
 return <div className="knob" role="slider" tabIndex={0} aria-label={`${axis.name} 노브`} aria-valuemin={1} aria-valuemax={5} aria-valuenow={value} aria-valuetext={`${axis.words[value-1]}, ${value}단계`} onKeyDown={e=>{const map={ArrowUp:value+1,ArrowRight:value+1,ArrowDown:value-1,ArrowLeft:value-1,Home:1,End:5};if(e.key in map){e.preventDefault();set(map[e.key])}}} onPointerDown={e=>{e.currentTarget.focus();const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*200-100,y=(e.clientY-r.top)/r.height*200-100;if(Math.hypot(x,y)>76){const angle=Math.atan2(x,-y)*180/Math.PI;if(Math.abs(angle)<=145)set(Math.round(angle/60)+3);return}start.current={y:e.clientY,v:value};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(start.current)set(start.current.v+Math.round((start.current.y-e.clientY)/28))}} onPointerUp={()=>start.current=null} onPointerCancel={()=>start.current=null}>
 <svg viewBox="0 0 200 200" aria-hidden="true">{axes[0].words.map((_,i)=><circle key={i} cx="100" cy="15" r={i===value-1?4:2} transform={`rotate(${(i-2)*60} 100 100)`}/>)}<circle cx="100" cy="100" r="73" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="100" cy="100" r="66"/><g transform={`rotate(${(value-3)*60} 100 100)`}><circle className="marker" cx="100" cy="48" r="4"/></g></svg>
 <div className="knob-copy" aria-hidden="true"><strong>{value}<small> / 5</small></strong><span>{axis.words[value-1]}</span></div></div>
}
function App(){const [selected,select]=useState(0),[values,change]=useState([3,3,3]);const axis=axes[selected],value=values[selected];const set=v=>change(old=>old.map((x,i)=>i===selected?v:x));return <main><header><span>MEGAFONT</span><span>조율 시안</span></header><h1>내 말의 느낌을<br/>직접 맞춰보세요.</h1><div className="sample" aria-label="견본"><span style={{transform:`scale(${[.7,.85,1,1.15,1.3][values[0]-1]}) skewX(${[0,0,0,-8,-16][values[1]-1]}deg)`,fontWeight:[300,400,500,700,900][values[2]-1]}}>내 생각은</span></div><div className="axis-buttons" aria-label="조절 항목">{axes.map((a,i)=><Button key={a.name} variant={i===selected?'default':'outline'} aria-pressed={selected===i} onClick={()=>select(i)}>{a.name}</Button>)}</div><Knob value={value} onChange={set} axis={axis}/><div className="ends"><span>{axis.ends[0]}</span><span>{axis.ends[1]}</span></div><p className="hint">눈금을 누르거나 위아래로 움직여보세요.</p><section className="compare"><div className="section-title"><h2>슬라이더로 비교하기</h2><span>{value} / 5</span></div><Slider aria-label={`${axis.name} 슬라이더`} aria-valuetext={`${axis.words[value-1]}, ${value}단계`} min={1} max={5} step={1} value={[value]} onValueChange={v=>set(v[0])}/></section><Button className="reset" variant="outline" onClick={()=>change([3,3,3])}>기본값으로</Button><footer>shadcn/ui Slider · Button을 활용한 별도 시안<br/>빠르기는 이 시안에서 글자 기울기로만 표시됩니다.</footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
